pipeline {    
    agent any
    tools {nodejs "node"}

    environment {
        CI = 'true'
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Build artifact') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Deploy'){
            steps {
                sh '/jenkins/scripts/deploy.sh'
            }
        }
    }
}
